# Generated by Django 5.1 on 2024-08-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_department_registerstudent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registerStudent',
            new_name='registeredStudent',
        ),
    ]
