# Generated by Django 5.1 on 2024-09-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
